<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Seeder;

class AllowedEmailSeeder extends Seeder
{
    /**
     * Liste des emails autorisés à se connecter via Google/Microsoft OAuth.
     * Format : ['email' => '...'] pour dériver le nom automatiquement,
     *           ['email' => '...', 'prenom' => '...', 'nom' => '...'] pour un nom explicite.
     */
    private array $entries = [
        // ── SuperAdmins (Développeurs PFA) ─────────────────────────────────
        ['email' => 'yassermoulaysm@gmail.com',   'prenom' => 'Yasser',  'nom' => 'Moulay', 'roles' => ['superAdmin', 'admin', 'etudiant']],
        ['email' => 'yasser_moulay@um5.ac.ma',    'prenom' => 'Yasser',  'nom' => 'Moulay', 'roles' => ['superAdmin', 'admin', 'etudiant']],
        ['email' => 'soumiya_goumi@um5.ac.ma',    'prenom' => 'Soumiya', 'nom' => 'Goumi',  'roles' => ['superAdmin', 'admin', 'etudiant']],
        // ── Étudiants autorisés ──────────────────────────────────────────
        ['email' => 'abdssamadabdaoui@gmail.com'],
        ['email' => 'naiathadj2006@gmail.com'],
        ['email' => 'aoualbassma@gmail.com'],
        ['email' => 'el.karizma.pro@gmail.com'],
        ['email' => 'khalilbelghiti041@gmail.com'],
        ['email' => 'kfourka@gmail.com'],
        ['email' => 'ben.said.fatima2006@gmail.com'],
        ['email' => 'mbouaidoun1408@gmail.com'],
        ['email' => 'soufianelghala123@gmail.com'],
        ['email' => 'mohamed.amine.elkabous.bus@gmail.com'],
        ['email' => 'anas.elqandili2005@gmail.com'],
        ['email' => 'nasrnasor2005@gmail.com'],
        ['email' => 'najmito8@gmail.com'],
        ['email' => 'ilyassigri2017@gmail.com'],
        ['email' => 'mouadjillar755@gmail.com'],
        ['email' => 'khadija12jlil@gmail.com'],
        ['email' => 'mohamedbouchoum2006@gmail.com'],
        ['email' => 'laabioua95@gmail.com'],
        ['email' => 'laanibazakaria@gmail.com'],
        ['email' => 'marouchmohamed567@gmail.com'],
        ['email' => 'aminaouaayi@gmail.com'],
        ['email' => 'fati.ouaatat@gmail.com'],
        ['email' => 'linarahouti27@gmail.com',   'prenom' => 'Lina',          'nom' => 'Rahouti'],
        ['email' => 'meryemeramdi05@gmail.com'],
        ['email' => 'sarbouteoussama@gmail.com'],
        ['email' => 'hamzasrayhe0@gmail.com'],
        ['email' => 'sara.tidili06@gmail.com'],
        ['email' => 'kholoudaabika@gmail.com'],
        ['email' => 'khalidaattar7@gmail.com'],
        ['email' => 'aittalebdouae@gmail.com'],
        ['email' => 'assiaaznag03@gmail.com'],
        ['email' => 'adambabouny@gmail.com'],
        ['email' => 'zinebelrhiti111@gmail.com'],
        ['email' => 'chakouriabderrahman@gmail.com'],
        ['email' => 'chikhiabdessamad888@gmail.com'],
        ['email' => 'hafsadamoun4@gmail.com'],
        ['email' => 'abdeladimelgouryani@gmail.com'],
        ['email' => 'fouknaadam@gmail.com'],
        ['email' => 'jirouhafida072@gmail.com'],
        ['email' => 'achrafkharfa755@gmail.com'],
        ['email' => 'asmaemarzaq2006@gmail.com',  'prenom' => 'Asmae',         'nom' => 'Marzaq'],
        ['email' => 'morghi5hajar@gmail.com'],
        ['email' => 'guizlaneoulbouj@gmail.com'],
        ['email' => 'sebbarhasnae230@gmail.com'],
        ['email' => 'narjisstahirialaoui@gmail.com'],
        ['email' => 'tourabiyahya54@gmail.com'],
        ['email' => 'simosaadhadji1@gmail.com'],
        ['email' => 'nadyaaitmoula5@gmail.com'],
        ['email' => 'ayaamiry@gmail.com'],
        ['email' => 'anesrahilyas@gmail.com'],
        ['email' => 'ansariayoub14@gmail.com'],
        ['email' => 'karimaatik18@gmail.com'],
        ['email' => 'ilyasff2006@gmail.com'],
        ['email' => 'nadiabaha21@gmail.com'],
        ['email' => 'nadabeloakda@gmail.com'],
        ['email' => 'mohamedbouhadi541@gmail.com'],
        ['email' => 'tahachouach829@gmail.com'],
        ['email' => 'alaoui.ines0526@gmail.com'],
        ['email' => 'fahimhind08@gmail.com'],
        ['email' => 'zaynabgougni@gmail.com'],
        ['email' => 'rania97hannaoui@gmail.com'],
        ['email' => 'hmamouch09youssef@gmail.com'],
        ['email' => 'niama10khadim@gmail.com'],
        ['email' => 'meriemlaabarta@gmail.com'],
        ['email' => 'largou6ahmed@gmail.com'],
        ['email' => 'amassalabi@gmail.com'],
        ['email' => 'alaemedrare25@gmail.com'],
        ['email' => 'hibamoussaddar@gmail.com'],
        ['email' => 'najattaalim207@gmail.com'],
        ['email' => 'ghizlanenory01@gmail.com'],
        ['email' => 'ozaid2268@gmail.com'],
        ['email' => 'maryemrabach@gmail.com'],
        ['email' => 'rhahlamohammed@gmail.com'],
        ['email' => 'rimerh1904@gmail.com'],
        ['email' => 'ghizlanesaadanihassani@gmail.com'],
        ['email' => 'soumayatagh34@gmail.com'],
        ['email' => 'ikramthajjit@gmail.com'],
        ['email' => 'chaimae62844@gmail.com'],
        ['email' => 'abouguenimoha@gmail.com'],
        ['email' => 'anassabm123456789@gmail.com'],
        ['email' => 'saraachahbar26@gmail.com'],
        ['email' => 'adamagazzar@gmail.com'],
        ['email' => 'zaynabamimi27@gmail.com'],
        ['email' => 'belabbesadnane1234@gmail.com'],
        ['email' => 'myhaytamwork@gmail.com'],
        ['email' => 'ayoub.benaissa2005@gmail.com'],
        ['email' => 'benammar.anas.pro@gmail.com'],
        ['email' => 'idrissberkni@gmail.com'],
        ['email' => 'chemsboufris@gmail.com'],
        ['email' => 'boughalebm27@gmail.com'],
        ['email' => 'chayabrassou.m@gmail.com'],
        ['email' => 'mohamedchetoui50@gmail.com'],
        ['email' => 'chaimaedoukkali2@gmail.com'],
        ['email' => 'youssefdounit75@gmail.com'],
        ['email' => 'imaneelbourekkadi1@gmail.com'],
        ['email' => 'elakriilyass@gmail.com'],
        ['email' => 'hajar.eljabiri.05.05@gmail.com'],
        ['email' => 'khadijaezzahir15@gmail.com'],
        ['email' => 'othmaneezzouak@gmail.com'],
        ['email' => 'ezzoughiomar@gmail.com'],
        ['email' => 'fadilhajar2005@gmail.com'],
        ['email' => 'ayathachimi0603@gmail.com'],
        ['email' => 'hamzysaad@gmail.com'],
        ['email' => 'hilalifz@outlook.com'],
        ['email' => 'ahmed.idbenadi@um5r.ac.ma'],
        ['email' => 'am.khouiti@edu.umi.ac.ma'],
        ['email' => 's.khouya58@gmail.com'],
        ['email' => 'naoufallchb@gmail.com'],
        ['email' => 'lamkademyassine876@gmail.com'],
        ['email' => 'malakmotribe@gmail.com'],
        ['email' => 'yassinemtioui39@gmail.com'],
        ['email' => 'mnnassrallah662@gmail.com'],
        ['email' => 'rahiouihind667@gmail.com'],
        ['email' => 'inesoussi10@gmail.com'],
        ['email' => 'salmasoussi100@gmail.com'],
        ['email' => 'douaetoubali@gmail.com'],
        ['email' => 'ayoubtouhami2005@gmail.com'],
        ['email' => 'hatimyougou21@gmail.com'],
        ['email' => 'narjisb2006@gmail.com'],
        ['email' => 'omarbahous88@gmail.com'],
        ['email' => 'chinigdoha@gmail.com'],
        ['email' => 'basmaechkoundi19@gmail.com'],
        ['email' => 'hibaelhadi592@gmail.com'],
        ['email' => 'yasserelabbadi16@gmail.com'],
        ['email' => 'ishak.el-kharroubi@uit.ac.ma'],
        ['email' => 'adamessassi19@gmail.com'],
        ['email' => 'salma.essoufi9158@gmail.com'],
        ['email' => 'ayafadil2005@gmail.com'],
        ['email' => 'ahmedhmidani10@gmail.com'],
        ['email' => 'imchtkaabdelhak@gmail.com'],
        ['email' => 'samia2labhalla@gmail.com'],
        ['email' => 'khadijamamoun91@gmail.com'],
        ['email' => 'medaminemarzoug56@gmail.com'],
        ['email' => 'h.montasir2005@gmail.com'],
        ['email' => 'salahmarine222@gmail.com'],
        ['email' => 'mohamedouaquad@gmail.com'],
        ['email' => 'yya200188@gmail.com'],
        ['email' => 'mohammedrabouh7@gmail.com'],
        ['email' => 'mohamedridaretbi@gmail.com'],
        ['email' => 'zhonghoudi@gmail.com'],
        ['email' => 'nassereddinesammad@gmail.com'],
        ['email' => 'maryemsbani@gmail.com'],
        ['email' => 'sebbarmouhcine16032006@gmail.com'],
        ['email' => 'linasiari1@gmail.com'],
        ['email' => 'youssefabbad2005@gmail.com'],
        ['email' => 'b.abisourour.c2022@lm6e.ma'],
        ['email' => 'achouhoussam6@gmail.com'],
        ['email' => 'achtchi.salma23@gmail.com'],
        ['email' => 'aitlabbadeh@gmail.com'],
        ['email' => 'assmaamerkad@gmail.com'],
        ['email' => 'amthouda@gmail.com'],
        ['email' => 'mohamed.amine.art2005@gmail.com'],
        ['email' => 'm195.766sq@gmail.com'],
        ['email' => 'belhilalidouae@gmail.com'],
        ['email' => 'bensaidsaad39@gmail.com'],
        ['email' => 'ahmedbenomar64@gmail.com'],
        ['email' => 'yasserbodaoud@gmail.com'],
        ['email' => 'workwithmorty@gmail.com'],
        ['email' => 'bougdidaya8@gmail.com'],
        ['email' => 'ilias.boukhris21@gmail.com'],
        ['email' => 'taha.chafik21@gmail.com'],
        ['email' => 'alichahboubi@gmail.com'],
        ['email' => 'yahyachalach3@gmail.com'],
        ['email' => 'bhllmanal@gmail.com'],
        ['email' => 'maryamchaouqi@gmail.com'],
        ['email' => 'chrorouz@gmail.com'],
        ['email' => 'kawtar36dakham@gmail.com'],
        ['email' => 'mldriouech04@gmail.com'],
        ['email' => 'elabedalynassiba@gmail.com'],
        ['email' => 'zouhairelaouad48@gmail.com'],
        ['email' => 'marwaelatlassi2005@gmail.com'],
        ['email' => 'khadijaazizi844@gmail.com'],
        ['email' => 'elferriaymane@gmail.com'],
        ['email' => 'elgaddaryass@gmail.com'],
        ['email' => 'abdollatif1976@gmail.com'],
        ['email' => 'ziyadi2006@gmail.com'],
        ['email' => 'oumamaelghadouini8@gmail.com'],
        ['email' => 'hamzaelmkiesss@gmail.com'],
        ['email' => 'essahmhoussam@gmail.com'],
        ['email' => 'ayaesskheifi2005@gmail.com'],
        ['email' => 'fathinisrine18072004@gmail.com'],
        ['email' => 'ammarfet00@gmail.com'],
        ['email' => 'yasser201v@gmail.com'],
        ['email' => 'rimhaigoun@gmail.com'],
        ['email' => 'mohamedkhalilibouchna99@gmail.com'],
        ['email' => 'ilane.sara@gsrstudent.ma'],
        ['email' => 'younesjaaidani02@gmail.com'],
        ['email' => 'kaddamikhalil@gmail.com'],
        ['email' => 'amine.karmouch@gmail.com'],
        ['email' => 'abderrahmanekhellou.4@gmail.com', 'prenom' => 'Abderrahmane', 'nom' => 'Khellou'],
        ['email' => 'lakhalchaimae96@gmail.com'],
        ['email' => 'khalidlamachi2005@gmail.com'],
        ['email' => 'vonijoli4@gmail.com'],
        ['email' => 'mbarkioukhadija@gmail.com'],
        ['email' => 'ambtwmlkn@gmail.com'],
        ['email' => 'salmamouhni2005@gmail.com'],
        ['email' => 'houdamou942@gmail.com'],
        ['email' => 'mohamedmsimer99@gmail.com'],
        ['email' => 'mimanan709@gmail.com'],
        ['email' => 'nafiselghali@gmail.com'],
        ['email' => 'karimoolahiane9@gmail.com'],
        ['email' => 'ismailoua016@gmail.com'],
        ['email' => 'm.ouisnaf@gmail.com'],
        ['email' => 'fe940680@gmail.com'],
        ['email' => 'redouanrab@gmail.com'],
        ['email' => 'aymaneman2006@gmail.com'],
        ['email' => 'sat.walid2004@gmail.com'],
        ['email' => 'isedrati9@gmail.com'],
        ['email' => 'sskoubani10@gmail.com'],
        ['email' => 'titi.abdelghafour@gmail.com'],
        ['email' => 'kacemamineyassine@gmail.com'],
        ['email' => 'sohai.yssef@gmail.com'],
        ['email' => 'sabirzougui2004@gmail.com'],
        ['email' => 'abghaynada@gmail.com'],
        ['email' => 'ihabadraoui42@gmail.com'],
        ['email' => 'ssama4965@gmail.com'],
        ['email' => 'achrafbaiz8888@gmail.com'],
        ['email' => 'wissalbarchan22@gmail.com'],
        ['email' => 'adambelhous2004@gmail.com'],
        ['email' => 'benabdellahamine7@gmail.com'],
        ['email' => 'salmaelhafiane@gmail.com'],
        ['email' => 'douaaelhamdaoui2005@gmail.com'],
        ['email' => 'amineelidirissi@gmail.com'],
        ['email' => 'ilyassettahiri2006@gmail.com'],
        ['email' => 'imaneichi5i@gmail.com'],
        ['email' => 'badrizou074@gmail.com'],
        ['email' => 'wiamlahboub57@gmail.com'],
        ['email' => 'rimlahrech05@gmail.com'],
        ['email' => 'lahyanyasmine@gmail.com'],
        ['email' => 'rihabcf2025@gmail.com'],
        ['email' => 'amine.oua97@gmail.com'],
        ['email' => 'kawtar.out05@gmail.com'],
        ['email' => 'aabirtansaoui16@gmail.com'],
        ['email' => 'htmtffh13@gmail.com'],
        ['email' => 'ghitatouil05@gmail.com'],
        ['email' => 'salmaabba24@gmail.com'],
        ['email' => 'arbaouiilyas4@gmail.com'],
        ['email' => 'mustaphabahman24@gmail.com'],
        ['email' => 'mariamatoupebalde3@gmail.com'],
        ['email' => 'camararoger004@gmail.com',         'prenom' => 'Roger',         'nom' => 'Camara'],
        ['email' => 'derrazoussama2005@gmail.com'],
        ['email' => 'elhansali2006meriem@gmail.com'],
        ['email' => 'abderrahman.el.kourrami@gmail.com'],
        ['email' => 'ibtissamelmorabit62@gmail.com'],
        ['email' => 'youshigouali@gmail.com'],
        ['email' => 'hamidouguindo602@gmail.com'],
        ['email' => 'fatimazahrahaoua384@gmail.com'],
        ['email' => 'mohamedaminehazil@gmail.com'],
        ['email' => 'aminekharmoudi022@gmail.com'],
        ['email' => 'anaslasfar3@gmail.com'],
        ['email' => 'marsomohamedyassine@gmail.com'],
        ['email' => 'mhiriznajoua@gmail.com'],
        ['email' => 'oabdullae@gmail.com'],
        ['email' => 'imaneouaghdoud@gmail.com'],
        ['email' => 'mariel.oumattotto21@gmail.com'],
        ['email' => 'alaeedineoumda2@gmail.com'],
        ['email' => 'hindrguig139@gmail.com'],
        ['email' => 'khaoularougui2005@gmail.com'],
        ['email' => 'ouailtahirielalaoui@gmail.com'],
        ['email' => 'manal547547@gmail.com'],
        ['email' => 'adamachamli22@gmail.com'],
        ['email' => 'amineachargui001@gmail.com'],
        ['email' => 'wilfreednouame@gmail.com'],
        ['email' => 'lahcenalibouch47@gmail.com'],
        ['email' => 'haitemarif14@gmail.com'],
        ['email' => 'marwabadsi1@gmail.com'],
        ['email' => 'malakchahbouni2006@gmail.com'],
        ['email' => 'linachaib9@gmail.com'],
        ['email' => 'saadcharaf992@gmail.com'],
        ['email' => 'diwalid24@gmail.com'],
        ['email' => 'nourdoutayeb6@gmail.com'],
        ['email' => 'elallali.hiba05@gmail.com'],
        ['email' => 'meryemeelfatouaki@gmail.com'],
        ['email' => 'elghzirisafae@gmail.com'],
        ['email' => 'lhabti222@gmail.com'],
        ['email' => 'hafssaeljemli06@gmail.com'],
        ['email' => 'aminelmouhrou010@gmail.com'],
        ['email' => 'yassineelkhlifi3@gmail.com'],
        ['email' => 'aymanelmerzouki21@gmail.com'],
        ['email' => 'yassineerchaicha@gmail.com'],
        ['email' => 'essakineabdallah@gmail.com'],
        ['email' => 'khalilessalmi4@gmail.com'],
        ['email' => 'soumiyagoumi70@gmail.com', 'prenom' => 'Soumiya', 'nom' => 'Goumi', 'roles' => ['superAdmin', 'admin', 'etudiant']],
        ['email' => 'mouadrca042@gmail.com'],
        ['email' => 'firdaous.hassainate@gmail.com'],
        ['email' => 'zahraihimmi455@gmail.com'],
        ['email' => 'younesseissourd@gmail.com'],
        ['email' => 'marwanjamraoui9@gmail.com'],
        ['email' => 'kabliadam17@gmail.com'],
        ['email' => 'kaboucheyoussef9@gmail.com'],
        ['email' => 'amalkamal.ak5@gmail.com'],
        ['email' => 'k.ali.pro@outlook.com'],
        ['email' => 'nkharkhouch@gmail.com'],
        ['email' => 'aymenklimo2006@gmail.com'],
        ['email' => 'nourelhoudalamkhanat@gmail.com'],
        ['email' => 'lemcharraqzoubida@gmail.com'],
        ['email' => 'soukainamjid01@gmail.com'],
        ['email' => 'soukainamostafa1@gmail.com'],
        ['email' => 'youssefmouhtadi06@gmail.com'],
        ['email' => 'nawal.mouladid@gmail.com'],
        ['email' => 'moulay.yas.fst@uhp.ac.ma', 'prenom' => 'Yasser', 'nom' => 'Moulay', 'roles' => ['superAdmin', 'admin', 'etudiant']],
        ['email' => 'knaciri871@gmail.com'],
        ['email' => 'mouadsaber396@gmail.com'],
        ['email' => 'anassmaataoui399@gmail.com'],
        ['email' => 'manalsahil89@gmail.com'],
        ['email' => 'saiifsalma128@gmail.com'],
        ['email' => 'sfrthatim@gmail.com'],
        ['email' => 'tahirihind2005@gmail.com'],
        ['email' => 'tchahanif5@gmail.com'],
        ['email' => 'imane6younsi@gmail.com'],
        ['email' => 'zikrimalak@gmail.com'],
        ['email' => 'yassirznaina@gmail.com'],
    ];

    public function run(): void
    {
        foreach ($this->entries as $entry) {
            $email = strtolower($entry['email']);

            if (isset($entry['prenom'])) {
                $prenom = $entry['prenom'];
                $nom    = $entry['nom'];
            } else {
                ['prenom' => $prenom, 'nom' => $nom] = $this->parseName($email);
            }

            User::updateOrCreate(
                ['emailInstitutionnel' => $email],
                [
                    'nom'          => $nom,
                    'prenom'       => $prenom,
                    'password'     => null,
                    'profileActif' => true,
                    'roles'        => $entry['roles'] ?? ['etudiant'],
                ]
            );
        }

        $this->command->info('✅ ' . count($this->entries) . ' utilisateurs autorisés seedés avec succès.');
    }

    /**
     * Dérive un prenom + nom depuis la partie locale de l'email.
     * Exemple : "ben.said.fatima2006" → prenom: Ben, nom: Said Fatima
     */
    private function parseName(string $email): array
    {
        $local   = explode('@', $email)[0];
        // Retirer les chiffres, tirets, underscores
        $cleaned = preg_replace('/[\d\-_]/', '', $local);
        // Séparer sur les points
        $parts   = array_values(array_filter(array_map('trim', explode('.', $cleaned))));

        if (empty($parts)) {
            return ['prenom' => 'Etudiant', 'nom' => 'ENSIAS'];
        }

        $prenom = ucfirst(strtolower($parts[0]));
        $nom    = count($parts) > 1
            ? ucwords(strtolower(implode(' ', array_slice($parts, 1))))
            : ucfirst(strtolower($parts[0]));

        return ['prenom' => $prenom, 'nom' => $nom];
    }
}
